### PR TITLE
Update Util.js

### PR DESCRIPTION
**Pull request by thehairy**
checks for object string and removes useless "isFalsey" function.
Ever heard of "!something"?

### CODE REVIEW

**Comment by wutv** [comment]
The object string is already in my local commit, and the isFalsey function is for checking whether a value is undefined, false or null

**Comment by wutv** [comment]
I don't want all falsey values that come with the ! operator

**Comment by thehairy** [comment]
Then simply change the way ! works lul

**Comment by wutv** [comment]
> Then simply change the way ! works lul

using a function is lesser work tho

**Comment by thehairy** [comment]
> > Then simply change the way ! works lul
> 
> using a function is lesser work tho

In the end, no, not at all.

**Comment by wutv** [comment]
also, wdym change the way ! works? change the functionality of the operator entirely?

**Pull request closed without merging**
